CREATE TABLE qrtz_scheduler(
  SCHED_NAME varchar(120) NOT NULL,
  HOSTNAME varchar(200) NOT NULL,
  PRIMARY KEY (SCHED_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE qrtz_database(
  DATABASE_ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME varchar(200) NOT NULL,
  TYPE varchar(20) NOT NULL,
  URL varchar(200) NOT NULL,
  USERNAME varchar(50) NOT NULL,
  PASSWORD varchar(200) NOT NULL,
  CREATION_DATE datetime NOT NULL,
  USER_ID int(11) NOT NULL,
  PRIMARY KEY (DATABASE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE qrtz_holiday(
  HOLIDAY_ID INTEGER NOT NULL AUTO_INCREMENT,
  HOLIDAY_DATE date NOT NULL,
  NAME varchar(200) NOT NULL,
  RECURRENT smallint(1) NOT NULL, 	
  CREATION_DATE datetime NOT NULL,
  USER_ID int(11) NOT NULL,
  PRIMARY KEY (HOLIDAY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE qrtz_calendars (
  SCHED_NAME varchar(120) NOT NULL,
  CALENDAR_NAME varchar(200) NOT NULL,
  CALENDAR blob NOT NULL,
  PRIMARY KEY (SCHED_NAME,CALENDAR_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE qrtz_job_details (
  SCHED_NAME varchar(120) NOT NULL,
  JOB_NAME varchar(200) NOT NULL,
  JOB_GROUP varchar(200) NOT NULL,
  DESCRIPTION varchar(250) DEFAULT NULL,
  JOB_CLASS_NAME varchar(250) NOT NULL,
  IS_DURABLE varchar(1) NOT NULL,
  IS_NONCONCURRENT varchar(1) NOT NULL,
  IS_UPDATE_DATA varchar(1) NOT NULL,
  REQUESTS_RECOVERY varchar(1) NOT NULL,
  JOB_DATA blob,
  PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE qrtz_job_config (
  SCHED_NAME varchar(120) NOT NULL,
  JOB_NAME varchar(200) NOT NULL,
  JOB_GROUP varchar(200) NOT NULL,
  JOB_TYPE INTEGER NOT NULL DEFAULT 0,
  JOB_SEQUENCE smallint(2) DEFAULT NULL,
  SMS_REDEFINED smallint(2) DEFAULT NULL,
  SMS_ENABLED smallint(2) DEFAULT NULL,
  SMS_LEVEL smallint(2) DEFAULT NULL,
  SMS_PERIOD smallint(2) DEFAULT NULL,
  PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE qrtz_job_param (
  SCHED_NAME varchar(120) NOT NULL,
  JOB_NAME varchar(200) NOT NULL,
  JOB_GROUP varchar(200) NOT NULL,
  KEY_PARAM varchar(50) NOT NULL,
  DESCRIPTION varchar(100) NOT NULL,
  PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP,KEY_PARAM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE qrtz_job_history (
  JOB_HISTORY_ID mediumint(9) NOT NULL AUTO_INCREMENT,
  SCHED_NAME varchar(120) NOT NULL,
  JOB_NAME varchar(200) NOT NULL,
  JOB_GROUP varchar(200) NOT NULL,
  FIRED_TIME datetime NOT NULL,
  END_TIME datetime NOT NULL,
  STATE varchar(16) NOT NULL,
  JOB_LOG longtext,
  PRIMARY KEY (JOB_HISTORY_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1581 DEFAULT CHARSET=utf8;

CREATE TABLE qrtz_triggers (
  SCHED_NAME varchar(120) NOT NULL,
  TRIGGER_NAME varchar(200) NOT NULL,
  TRIGGER_GROUP varchar(200) NOT NULL,
  JOB_NAME varchar(200) NOT NULL,
  JOB_GROUP varchar(200) NOT NULL,
  DESCRIPTION varchar(250) DEFAULT NULL,
  NEXT_FIRE_TIME bigint(13) DEFAULT NULL,
  PREV_FIRE_TIME bigint(13) DEFAULT NULL,
  PRIORITY int(11) DEFAULT NULL,
  TRIGGER_STATE varchar(16) NOT NULL,
  TRIGGER_TYPE varchar(8) NOT NULL,
  START_TIME bigint(13) NOT NULL,
  END_TIME bigint(13) DEFAULT NULL,
  CALENDAR_NAME varchar(200) DEFAULT NULL,
  MISFIRE_INSTR smallint(2) DEFAULT NULL,
  JOB_DATA blob,
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  KEY SCHED_NAME (SCHED_NAME,JOB_NAME,JOB_GROUP),
  CONSTRAINT qrtz_triggers_ibfk_1 FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP) REFERENCES qrtz_job_details (SCHED_NAME, JOB_NAME, JOB_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE qrtz_fired_triggers (
  SCHED_NAME varchar(120) NOT NULL,
  ENTRY_ID varchar(95) NOT NULL,
  TRIGGER_NAME varchar(200) NOT NULL,
  TRIGGER_GROUP varchar(200) NOT NULL,
  INSTANCE_NAME varchar(200) NOT NULL,
  FIRED_TIME bigint(13) NOT NULL,
  PRIORITY int(11) NOT NULL,
  STATE varchar(16) NOT NULL,
  JOB_NAME varchar(200) DEFAULT NULL,
  JOB_GROUP varchar(200) DEFAULT NULL,
  IS_NONCONCURRENT varchar(1) DEFAULT NULL,
  REQUESTS_RECOVERY varchar(1) DEFAULT NULL,
  PRIMARY KEY (SCHED_NAME,ENTRY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE qrtz_paused_trigger_grps (
  SCHED_NAME varchar(120) NOT NULL,
  TRIGGER_GROUP varchar(200) NOT NULL,
  PRIMARY KEY (SCHED_NAME,TRIGGER_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE qrtz_simple_triggers (
  SCHED_NAME varchar(120) NOT NULL,
  TRIGGER_NAME varchar(200) NOT NULL,
  TRIGGER_GROUP varchar(200) NOT NULL,
  REPEAT_COUNT bigint(7) NOT NULL,
  REPEAT_INTERVAL bigint(12) NOT NULL,
  TIMES_TRIGGERED bigint(10) NOT NULL,
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  CONSTRAINT qrtz_simple_triggers_ibfk_1 FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES qrtz_triggers (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE qrtz_simprop_triggers (
  SCHED_NAME varchar(120) NOT NULL,
  TRIGGER_NAME varchar(200) NOT NULL,
  TRIGGER_GROUP varchar(200) NOT NULL,
  STR_PROP_1 varchar(512) DEFAULT NULL,
  STR_PROP_2 varchar(512) DEFAULT NULL,
  STR_PROP_3 varchar(512) DEFAULT NULL,
  INT_PROP_1 int(11) DEFAULT NULL,
  INT_PROP_2 int(11) DEFAULT NULL,
  LONG_PROP_1 bigint(20) DEFAULT NULL,
  LONG_PROP_2 bigint(20) DEFAULT NULL,
  DEC_PROP_1 decimal(13,4) DEFAULT NULL,
  DEC_PROP_2 decimal(13,4) DEFAULT NULL,
  BOOL_PROP_1 varchar(1) DEFAULT NULL,
  BOOL_PROP_2 varchar(1) DEFAULT NULL,
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  CONSTRAINT qrtz_simprop_triggers_ibfk_1 FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES qrtz_triggers (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE qrtz_veto_triggers (
  VETO_ID mediumint(9) NOT NULL AUTO_INCREMENT,
  SCHED_NAME varchar(120) NOT NULL,
  TRIGGER_NAME varchar(200) NOT NULL,
  TRIGGER_GROUP varchar(200) NOT NULL,
  VETO_TIME bigint(20) NOT NULL,
  USERID varchar(10) NOT NULL,
  REASON varchar(100) NOT NULL,
  PRIMARY KEY (VETO_ID)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;

CREATE TABLE qrtz_blob_triggers (
  SCHED_NAME varchar(120) NOT NULL,
  TRIGGER_NAME varchar(200) NOT NULL,
  TRIGGER_GROUP varchar(200) NOT NULL,
  BLOB_DATA blob,
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  CONSTRAINT qrtz_blob_triggers_ibfk_1 FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES qrtz_triggers (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE qrtz_cron_triggers (
  SCHED_NAME varchar(120) NOT NULL,
  TRIGGER_NAME varchar(200) NOT NULL,
  TRIGGER_GROUP varchar(200) NOT NULL,
  CRON_EXPRESSION varchar(200) NOT NULL,
  TIME_ZONE_ID varchar(80) DEFAULT NULL,
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  CONSTRAINT qrtz_cron_triggers_ibfk_1 FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES qrtz_triggers (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE qrtz_locks (
  SCHED_NAME varchar(120) NOT NULL,
  LOCK_NAME varchar(40) NOT NULL,
  PRIMARY KEY (SCHED_NAME,LOCK_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE qrtz_scheduler_state (
  SCHED_NAME varchar(120) NOT NULL,
  INSTANCE_NAME varchar(200) NOT NULL,
  LAST_CHECKIN_TIME bigint(13) NOT NULL,
  CHECKIN_INTERVAL bigint(13) NOT NULL,
  PRIMARY KEY (SCHED_NAME,INSTANCE_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE REF_CODES (
	REF_CODE_ID INTEGER NOT NULL AUTO_INCREMENT,
	DOMAIN VARCHAR(50) NOT NULL,
	LOW_VALUE INTEGER,
	HIGH_VALUE INTEGER,
	CHAR_VALUE CHAR(1),
	DATE_VALUE DATE,
	DESCRIPTION VARCHAR(100) NOT NULL,
	PRIMARY KEY (REF_CODE_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1581 DEFAULT CHARSET=utf8;

INSERT INTO REF_CODES ( DOMAIN, LOW_VALUE, HIGH_VALUE, CHAR_VALUE, DATE_VALUE, DESCRIPTION ) VALUES ( 'QUARTZ_LEVEL', 1, null, null, null, 'Per group' );
INSERT INTO REF_CODES ( DOMAIN, LOW_VALUE, HIGH_VALUE, CHAR_VALUE, DATE_VALUE, DESCRIPTION ) VALUES ( 'QUARTZ_LEVEL', 2, null, null, null, 'Per service' );

INSERT INTO REF_CODES ( DOMAIN, LOW_VALUE, HIGH_VALUE, CHAR_VALUE, DATE_VALUE, DESCRIPTION ) VALUES ( 'QUARTZ_PERIOD_GROUP', 1, null, null, null, 'Begining of group execution' );
INSERT INTO REF_CODES ( DOMAIN, LOW_VALUE, HIGH_VALUE, CHAR_VALUE, DATE_VALUE, DESCRIPTION ) VALUES ( 'QUARTZ_PERIOD_GROUP', 2, null, null, null, 'Ending of group excution' );
INSERT INTO REF_CODES ( DOMAIN, LOW_VALUE, HIGH_VALUE, CHAR_VALUE, DATE_VALUE, DESCRIPTION ) VALUES ( 'QUARTZ_PERIOD_GROUP', 3, null, null, null, 'Begining/Ending of group execution' );

INSERT INTO REF_CODES ( DOMAIN, LOW_VALUE, HIGH_VALUE, CHAR_VALUE, DATE_VALUE, DESCRIPTION ) VALUES ( 'QUARTZ_PERIOD_SERVICE', 1, null, null, null, 'Begining of service execution' );
INSERT INTO REF_CODES ( DOMAIN, LOW_VALUE, HIGH_VALUE, CHAR_VALUE, DATE_VALUE, DESCRIPTION ) VALUES ( 'QUARTZ_PERIOD_SERVICE', 2, null, null, null, 'Ending  of service execution' );
INSERT INTO REF_CODES ( DOMAIN, LOW_VALUE, HIGH_VALUE, CHAR_VALUE, DATE_VALUE, DESCRIPTION ) VALUES ( 'QUARTZ_PERIOD_SERVICE', 3, null, null, null, 'Begining/Ending of service execution' );

INSERT INTO REF_CODES ( DOMAIN, LOW_VALUE, HIGH_VALUE, CHAR_VALUE, DATE_VALUE, DESCRIPTION ) VALUES ( 'QUARTZ_PERIOD_GROUPED_SERVICE', 1, null, null, null, 'Begining of each service execution' );
INSERT INTO REF_CODES ( DOMAIN, LOW_VALUE, HIGH_VALUE, CHAR_VALUE, DATE_VALUE, DESCRIPTION ) VALUES ( 'QUARTZ_PERIOD_GROUPED_SERVICE', 2, null, null, null, 'Ending of each service execution' );
INSERT INTO REF_CODES ( DOMAIN, LOW_VALUE, HIGH_VALUE, CHAR_VALUE, DATE_VALUE, DESCRIPTION ) VALUES ( 'QUARTZ_PERIOD_GROUPED_SERVICE', 3, null, null, null, 'Beging/Ending of service execution' );


